version: '3.5'
services:
    db:
        image: postgres:14
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_USER=assert
            - POSTGRES_DB=topics_bot
            - POSTGRES_PASSWORD=KhERp2ni_ALpRMdv3paBJUG-hVOryTu0
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
